### ISSUE TITLE
Not working???

### ISSUE THREAD

**Issue by kirito9723** [MrG3P5/Domain-Grabber#1]
When I run the script and choose tld or date i wait but nothing no result but previous version I was getting result..... I hope you fix it

**Comment by MrG3P5** [comment]
can you give me screenshot about that?

**Comment by kirito9723** [comment]
> can you give me screenshot about that?

![ddd](https://user-images.githubusercontent.com/49051809/226168173-77000f5e-442c-4ca3-87af-1d23c7618209.PNG)
![Capture](https://user-images.githubusercontent.com/49051809/226168177-2e8e9b91-3f57-4ab0-bbf4-d134ad7ca02b.PNG)

After 30 sec
The date exit and tld freeze

**Comment by kirito9723** [comment]
I wait some time and tld finnish but no result (there is no result.txt)

**Comment by MrG3P5** [comment]
ohh im forgot bro result folder,, try to clone this repo again

**Comment by MrG3P5** [comment]
ohh im forgot bro result folder,, try to clone this repo again
