### ISSUE TITLE
Grab by Date not Working!!

### ISSUE THREAD

**Issue by kirito9723** [MrG3P5/Domain-Grabber#2]
Hi again , the tld is working but when I use date the script finished without resulte ... These pictures..and think you ♥️
![new 2](https://user-images.githubusercontent.com/49051809/227779412-739ea8f2-a4e8-4d89-83d0-4a2d2836fbfd.PNG)
![new](https://user-images.githubusercontent.com/49051809/227779415-ec00af30-ad69-4845-aeb4-0ac038150de6.PNG)

**Comment by MrG3P5** [comment]
![Screenshot_2023-03-26_18_25_37](https://user-images.githubusercontent.com/57594747/227800955-943bc9e5-89d7-4f49-987b-09e580915949.png)
